name: amihub
description: A new Flutter project.

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.

  cupertino_icons: ^0.1.2
  flutter_webview_plugin: ^0.3.5
  webview_flutter:
  shared_preferences: ^0.5.3+4
  http_interceptor: ^0.0.3
  backdrop: ^0.1.8
  random_color:
  flutter_datetime_picker: ^1.2.6
  dots_indicator: ^1.0.0
  sembast: ^2.1.0
  path_provider:
  sqflite:





dev_dependencies:
  flutter_test:
    sdk: flutter




# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/amihub.png
    - assets/logo.png
    - assets/authentication.png
  fonts:
    - family: Raleway
      fonts:
        - asset: fonts/Raleway-Black.ttf
        - asset: fonts/Raleway-BlackItalic.ttf
        - asset: fonts/Raleway-Bold.ttf
        - asset: fonts/Raleway-BoldItalic.ttf
        - asset: fonts/Raleway-Light.ttf
        - asset: fonts/Raleway-LightItalic.ttf
        - asset: fonts/Raleway-Medium.ttf
        - asset: fonts/Raleway-MediumItalic.ttf
        - asset: fonts/Raleway-Regular.ttf
        - asset: fonts/Raleway-Thin.ttf
        - asset: fonts/Raleway-ThinItalic.ttf
          style: italic
    - family: Playfair
      fonts:
        - asset: fonts/PlayFair/PlayfairDisplay-Regular.ttf
        - asset: fonts/PlayFair/PlayfairDisplay-RegularItalic.ttf
          style: italic
        - asset: fonts/PlayFair/PlayfairDisplay-Bold.ttf
          weight: 700
        - asset: fonts/PlayFair/PlayfairDisplay-Black.ttf
          weight: 900
    - family: OpenSans
      fonts:
        - asset: fonts/OpenSans-Regular.ttf


  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
